export const HOME_FETCH_LOGIN_BEGIN = 'HOME_FETCH_LOGIN_BEGIN';
export const HOME_FETCH_LOGIN_SUCCESS = 'HOME_FETCH_LOGIN_SUCCESS';
export const HOME_FETCH_LOGIN_FAILURE = 'HOME_FETCH_LOGIN_FAILURE';
export const HOME_FETCH_LOGIN_DISMISS_ERROR = 'HOME_FETCH_LOGIN_DISMISS_ERROR';
