export const ADMIN_SET_SIDE_MENU_BEGIN = 'ADMIN_SET_SIDE_MENU_BEGIN';
export const ADMIN_SET_SIDE_MENU_SUCCESS = 'ADMIN_SET_SIDE_MENU_SUCCESS';
export const ADMIN_SET_SIDE_MENU_FAILURE = 'ADMIN_SET_SIDE_MENU_FAILURE';
export const ADMIN_SET_SIDE_MENU_DISMISS_ERROR = 'ADMIN_SET_SIDE_MENU_DISMISS_ERROR';
export const ADMIN_SET_SIDE_SELECTED = 'ADMIN_SET_SIDE_SELECTED';
